### ISSUE TITLE
关于展示格式的一点小建议

### ISSUE THREAD

**Issue by No-Github** [davidcheyenneone/CTF#1]
建议师傅可以使用 markdown 格式记录 writeup,gitbook 支持直接渲染 markdown 格式的笔记。

![Snipaste_2020-12-17_19-37-53](https://user-images.githubusercontent.com/18167071/102483236-65fd2a00-409f-11eb-9b93-c032380d8934.png)

在gitbook中直接关联 github 项目即可。例如我的这个writeup [2020-9-G60攻防大赛.md](https://github.com/No-Github/1earn/blob/master/1earn/Security/CTF/writeup/2020-9-G60%E6%94%BB%E9%98%B2%E5%A4%A7%E8%B5%9B.md)，在 gitbook 中直接是可读的 [2020-9-G60攻防大赛](https://ffffffff0x.gitbook.io/1earn/1earn/security/ctf/writeup/20209g60-gong-fang-da-sai)

**Comment by davidcheyenneone** [comment]
谢谢，因为原本是个人笔记，没有预料到将来会公开，所以记录时就没有太关注格式，导致现在要修改展示格式工程量比较大。回头我会研究一下markdown然后尽可能把笔记格式重新整理一遍的。
